### ISSUE TITLE
seek for help

### ISSUE THREAD

**Issue by jingjing-xu6** [iamaaditya/robust-activation-maps#1]
Hello, I would like to ask which paper you refer to for this code, thank you！

**Comment by iamaaditya** [comment]
Full paper (part of which is Robust CAM) https://arxiv.org/pdf/1801.08926.pdf
Short paper (2 pages, meant for workshop) https://vision.soic.indiana.edu/bright-and-dark-workshop-2018/cvcops_2018_extended_abstracts/robust-discriminative-localization.pdf

**Comment by jingjing-xu6** [comment]
I would like to ask if you can provide the train code，thanks！

**Comment by iamaaditya** [comment]
Training code for such maps are here: 
https://github.com/iamaaditya/image-compression-cnn

**Comment by jingjing-xu6** [comment]
Thanks so much for response
